
apiVersion: v1

kind: Pod

metadata:
  name: mrt-preview
  labels:
    app: mrt-preview

spec:

  hostname: mrt-preview

  containers:

  - name: otel-collector
    image: docker.io/otel/opentelemetry-collector-contrib:0.76.1
    args:
    - --config=/etc/otel-collector-config.yml
    ports:
    - hostPort: 24317
      containerPort: 4317
    - hostPort: 24318
      containerPort: 4318
    - hostPort: 28888
      containerPort: 8888
    volumeMounts:
    - mountPath: /etc/otel-collector-config.yml
      name: otel-config

  - name: node
    image: docker.io/inputoutput/cardano-node:1.35.4
    command:
    - /usr/local/bin/entrypoint
    env:
    - name: NETWORK
      value: preview
    volumeMounts:
    - mountPath: /ipc
      name: shared
    - mountPath: /data/db
      name: node-db

  - name: chain-indexer
    image: docker.io/bwbush/marlowe-chain-indexer:5526fb77f12b61213c595ba254c412792e4749ee
    depends_on:
    - node
    env:
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    - name: NODE_CONFIG
      value: /ipc/config/node.json
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preview
    - name: HTTP_PORT
      value: 3781
    - name: OTEL_SERVICE_NAME
      value: preview-chain-indexer
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preview:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 23781
      containerPort: 3781
    volumeMounts:
    - mountPath: /ipc
      name: shared
    - mountPath: /data/db
      name: node-db

  - name: chain-sync
    image: docker.io/bwbush/marlowe-chain-sync:5526fb77f12b61213c595ba254c412792e4749ee
    depends_on:
    - node
    env:
    - name: HOST
      value: mrt-preview
    - name: PORT
      value: 3715
    - name: QUERY_PORT
      value: 3716
    - name: JOB_PORT
      value: 3720
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    - name: NODE_CONFIG
      value: /ipc/config/node.json
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preview
    - name: HTTP_PORT
      value: 3782
    - name: OTEL_SERVICE_NAME
      value: preview-chain-sync
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preview:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 23715
      containerPort: 3715
    - hostPort: 23716
      containerPort: 3716
    - hostPort: 23720
      containerPort: 3720
    - hostPort: 23782
      containerPort: 3782
    volumeMounts:
    - mountPath: /ipc
      name: shared

  - name: marlowe-indexer
    image: docker.io/bwbush/marlowe-indexer:5526fb77f12b61213c595ba254c412792e4749ee
    depends_on:
    - chain-sync
    env:
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preview
    - name: MARLOWE_CHAIN_SYNC_HOST
      value: mrt-preview
    - name: MARLOWE_CHAIN_SYNC_PORT
      value: 3715
    - name: MARLOWE_CHAIN_SYNC_QUERY_PORT
      value: 3716
    - name: HTTP_PORT
      value: 3783
    - name: OTEL_SERVICE_NAME
      value: preview-marlowe-indexer
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preview:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 23783
      containerPort: 3783

  - name: marlowe-sync
    image: docker.io/bwbush/marlowe-sync:5526fb77f12b61213c595ba254c412792e4749ee
    env:
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preview
    - name: HOST
      value: mrt-preview
    - name: MARLOWE_SYNC_PORT
      value: 3724
    - name: MARLOWE_HEADER_SYNC_PORT
      value: 3725
    - name: MARLOWE_QUERY_PORT
      value: 3726
    - name: HTTP_PORT
      value: 3784
    - name: OTEL_SERVICE_NAME
      value: preview-marlowe-sync
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preview:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 23724
      containerPort: 3724
    - hostPort: 23725
      containerPort: 3725
    - hostPort: 23726
      containerPort: 3726
    - hostPort: 23784
      containerPort: 3784
  
  - name: contract
    image: docker.io/bwbush/marlowe-contract:5526fb77f12b61213c595ba254c412792e4749ee
    env:
    - name: HOST
      value: mrt-preview
    - name: PORT
      value: 3727
    - name: QUERY_PORT
      value: 3728
    - name: STORE_DIR
      value: /store
    - name: HTTP_PORT
      value: 3786
    - name: OTEL_SERVICE_NAME
      value: preview-marlowe-contract
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preview:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 23727
      containerPort: 3727
    - hostPort: 23728
      containerPort: 3728
    - hostPort: 23786
      containerPort: 3786
    volumeMounts:
    - mountPath: /store
      name: contracts
  
  - name: tx
    image: docker.io/bwbush/marlowe-tx:5526fb77f12b61213c595ba254c412792e4749ee
    depends_on:
    - chain-sync
    env:
    - name: HOST
      value: mrt-preview
    - name: PORT
      value: 3723
    - name: MARLOWE_CHAIN_SYNC_HOST
      value: mrt-preview
    - name: MARLOWE_CHAIN_SYNC_PORT
      value: 3715
    - name: MARLOWE_CHAIN_SYNC_QUERY_PORT
      value: 3716
    - name: MARLOWE_CHAIN_SYNC_COMMAND_PORT
      value: 3720
    - name: HTTP_PORT
      value: 3785
    - name: CONTRACT_HOST
      value: mrt-preprod
    - name: CONTRACT_QUERY_PORT
      value: 3728
    - name: OTEL_SERVICE_NAME
      value: preview-marlowe-tx
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preview:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 23723
      containerPort: 3723
    - hostPort: 23785
      containerPort: 3785
  
  - name: proxy
    image: docker.io/bwbush/marlowe-proxy:5526fb77f12b61213c595ba254c412792e4749ee
    depends_on:
    - marlowe-sync
    - tx
    - contract
    env:
    - name: HOST
      value: mrt-preview
    - name: PORT
      value: 3700
    - name: TRACED_PORT
      value: 3701
    - name: SYNC_HOST
      value: mrt-preview
    - name: MARLOWE_SYNC_PORT
      value: 3724
    - name: MARLOWE_HEADER_SYNC_PORT
      value: 3725
    - name: MARLOWE_QUERY_PORT
      value: 3726
    - name: CONTRACT_HOST
      value: mrt-preview
    - name: LOAD_PORT
      value: 3727
    - name: CONTRACT_QUERY_PORT
      value: 3728
    - name: TX_HOST
      value: mrt-preview
    - name: TX_PORT
      value: 3723
    - name: HTTP_PORT
      value: 3787
    - name: OTEL_SERVICE_NAME
      value: preview-marlowe-proxy
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preview:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 23700
      containerPort: 3700
    - hostPort: 23701
      containerPort: 3701
    - hostPort: 23787
      containerPort: 3787
  
  - name: web-server
    image: docker.io/bwbush/marlowe-web-server:5526fb77f12b61213c595ba254c412792e4749ee
    depends_on:
    - proxy
    env:
    - name: PORT
      value: 3780
    - name: RUNTIME_HOST
      value: mrt-preview
    - name: RUNTIME_PORT
      value: 3701
    - name: OTEL_SERVICE_NAME
      value: preview-marlowe-web-server
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preview:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 23780
      containerPort: 3780

  volumes:
  - name: otel-config
    hostPath:
      type: File
      path: ./config/otel-collector-config.yml
  - name: shared
    hostPath:
      type: Directory
      path: ./.
  - name: contracts
    hostPath:
      type: Directory
      path: ./contracts
  - name: node-db
    hostPath:
      type: Directory
      path: ./node.db

  restartPolicy: Always
  enableServiceLinks: false
  automountServiceAccountToken: false

status: {}

