
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: logging
  name: logging

spec:

  hostname: jaeger-logging

  containers:

  - name: jaeger
    image: docker.io/jaegertracing/all-in-one:latest
    args:
    - --memory.max-traces
    - "10000"
    - --query.base-path
    - /jaeger/ui
    env:
    - name: COLLECTOR_OTLP_ENABLED
      value: "true"
    ports:
    - hostPort: 16686
      containerPort: 16686
    - hostPort: 4317
      containerPort: 4317
    securityContext:
      capabilities: {}
    volumeMounts:
    - mountPath: /tmp
      name: shared
    resources:
      limits:
        memory: 32Gi

  enableServiceLinks: false
  automountServiceAccountToken: false
  restartPolicy: Always
  volumes:
  - hostPath:
      path: ./tmp
      type: Directory
    name: shared

status: {}

