apiVersion: v1
kind: Pod
metadata:
  name: mrx-mainnet
  labels:
    app: mrx-mainnet
spec:
  hostname: mrx-mainnet
  containers:
  - name: ici
    image: ghcr.io/functionally/marlowe-ici:latest
    args:
      - --ipfs-api
      - /ip4/192.168.0.12/tcp/5001
      - --host
      - mrt-mainnet
      - --port
      - 3700
      - --ipns-key
      - marlowe-ici-mainnet
      - --batch-slot
      - 110000000
  volumes:
  - name: shared
    hostPath:
      type: Directory
      path: ./.
  - name: keys
    hostPath:
      type: Directory
      path: ./keys
  restartPolicy: Always
