
apiVersion: v1

kind: Pod

metadata:
  name: mrt-preprod
  labels:
    app: mrt-preprod

spec:

  hostname: mrt-preprod

  containers:

  - name: node
    image: docker.io/inputoutput/cardano-node:1.35.4
    command:
    - /usr/local/bin/entrypoint
    env:
    - name: NETWORK
      value: preprod
    volumeMounts:
    - mountPath: /ipc
      name: shared
    - mountPath: /data/db
      name: node-db

  - name: chain-indexer
    image: ghcr.io/input-output-hk/marlowe-chain-indexer:0.0.3
    depends_on:
    - node
    env:
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    - name: NODE_CONFIG
      value: /ipc/config/node.json
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HTTP_PORT
      value: 3781
    ports:
    - hostPort: 13781
      containerPort: 3781
    volumeMounts:
    - mountPath: /ipc
      name: shared
    - mountPath: /data/db
      name: node-db

  - name: chain-sync
    image: ghcr.io/input-output-hk/marlowe-chain-sync:0.0.3
    depends_on:
    - node
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3715
    - name: QUERY_PORT
      value: 3716
    - name: JOB_PORT
      value: 3720
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    - name: NODE_CONFIG
      value: /ipc/config/node.json
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HTTP_PORT
      value: 3782
    ports:
    - hostPort: 13715
      containerPort: 3715
    - hostPort: 13716
      containerPort: 3716
    - hostPort: 13720
      containerPort: 3720
    - hostPort: 13782
      containerPort: 3782
    volumeMounts:
    - mountPath: /ipc
      name: shared

  - name: marlowe-indexer
    image: ghcr.io/input-output-hk/marlowe-indexer:0.0.3
    depends_on:
    - chain-sync
    env:
    - name: MARLOWE_CHAIN_SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_CHAIN_SYNC_PORT
      value: 3715
    - name: MARLOWE_CHAIN_SYNC_QUERY_PORT
      value: 3716
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HTTP_PORT
      value: 3783
    ports:
    - hostPort: 13783
      containerPort: 3783

  - name: marlowe-sync
    image: ghcr.io/input-output-hk/marlowe-sync:0.0.3
    env:
    - name: HOST
      value: mrt-preprod
    - name: MARLOWE_SYNC_PORT
      value: 3724
    - name: MARLOWE_HEADER_SYNC_PORT
      value: 3725
    - name: MARLOWE_QUERY_PORT
      value: 3726
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HTTP_PORT
      value: 3784
    ports:
    - hostPort: 13724
      containerPort: 3724
    - hostPort: 13725
      containerPort: 3725
    - hostPort: 13726
      containerPort: 3726
    - hostPort: 13784
      containerPort: 3784
  
  - name: contract
    image: ghcr.io/input-output-hk/marlowe-contract:0.0.3
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3727
    - name: QUERY_PORT
      value: 3728
    - name: STORE_DIR
      value: /store
    - name: HTTP_PORT
      value: 3786
    ports:
    - hostPort: 13727
      containerPort: 3727
    - hostPort: 13728
      containerPort: 3728
    - hostPort: 13786
      containerPort: 3786
    volumeMounts:
    - mountPath: /store
      name: contracts
  
  - name: tx
    image: ghcr.io/input-output-hk/marlowe-tx:0.0.3
    depends_on:
    - chain-sync
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3723
    - name: MARLOWE_CHAIN_SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_CHAIN_SYNC_PORT
      value: 3715
    - name: MARLOWE_CHAIN_SYNC_QUERY_PORT
      value: 3716
    - name: MARLOWE_CHAIN_SYNC_COMMAND_PORT
      value: 3720
    - name: CONTRACT_HOST
      value: mrt-preprod
    - name: CONTRACT_QUERY_PORT
      value: 3728
    - name: HTTP_PORT
      value: 3785
    ports:
    - hostPort: 13723
      containerPort: 3723
    - hostPort: 13785
      containerPort: 3785
  
  - name: proxy
    image: ghcr.io/input-output-hk/marlowe-proxy:0.0.3
    depends_on:
    - marlowe-sync
    - tx
    - contract
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3700
    - name: TRACED_PORT
      value: 3701
    - name: TX_HOST
      value: mrt-preprod
    - name: TX_PORT
      value: 3723
    - name: SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_SYNC_PORT
      value: 3724
    - name: MARLOWE_HEADER_SYNC_PORT
      value: 3725
    - name: MARLOWE_QUERY_PORT
      value: 3726
    - name: CONTRACT_HOST
      value: mrt-preprod
    - name: LOAD_PORT
      value: 3727
    - name: CONTRACT_QUERY_PORT
      value: 3728
    - name: HTTP_PORT
      value: 3787
    ports:
    - hostPort: 13700
      containerPort: 3700
    - hostPort: 13701
      containerPort: 3701
    - hostPort: 13787
      containerPort: 3787
  
  - name: web-server
    image: ghcr.io/input-output-hk/marlowe-web-server:0.0.3
    depends_on:
    - proxy
    env:
    - name: PORT
      value: 3780
    - name: RUNTIME_HOST
      value: mrt-preprod
    - name: RUNTIME_PORT
      value: 3701
    ports:
    - hostPort: 3780
      containerPort: 3780

  volumes:
  - name: shared
    hostPath:
      type: Directory
      path: ./.
  - name: contracts
    hostPath:
      type: Directory
      path: ./contracts
  - name: node-db
    hostPath:
      type: Directory
      path: ./node.db

  restartPolicy: Always
  enableServiceLinks: false
  automountServiceAccountToken: false

status: {}

