
apiVersion: v1
kind: Pod
metadata:
  name: mrt-preprod
  labels:
    app: mrt-preprod
spec:
  hostname: mrt-preprod
  containers:

  - name: node
    image: docker.io/inputoutput/cardano-node:8.1.2
    command:
    - /usr/local/bin/entrypoint
    env:
    - name: NETWORK
      value: preprod
    volumeMounts:
    - mountPath: /ipc
      name: shared
    - mountPath: /data/db
      name: node-db

  - name: chain-indexer
    image: ghcr.io/functionally/marlowe-chain-indexer:latest
    depends_on:
    - node
    env:
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    - name: NODE_CONFIG
      value: /ipc/config/node.json
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HTTP_PORT
      value: 3781
    volumeMounts:
    - mountPath: /ipc
      name: shared
    - mountPath: /data/db
      name: node-db

  - name: chain-sync
    image: ghcr.io/functionally/marlowe-chain-sync:latest
    depends_on:
    - node
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3715
    - name: QUERY_PORT
      value: 3716
    - name: JOB_PORT
      value: 3720
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    - name: NODE_CONFIG
      value: /ipc/config/node.json
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HTTP_PORT
      value: 3782
    volumeMounts:
    - mountPath: /ipc
      name: shared

  - name: marlowe-indexer
    image: ghcr.io/functionally/marlowe-indexer:latest
    depends_on:
    - chain-sync
    env:
    - name: MARLOWE_CHAIN_SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_CHAIN_SYNC_PORT
      value: 3715
    - name: MARLOWE_CHAIN_SYNC_QUERY_PORT
      value: 3716
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HTTP_PORT
      value: 3783

  - name: marlowe-sync
    image: ghcr.io/functionally/marlowe-sync:latest
    env:
    - name: MARLOWE_CHAIN_SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_CHAIN_SYNC_QUERY_PORT
      value: 3716
    - name: HOST
      value: mrt-preprod
    - name: MARLOWE_SYNC_PORT
      value: 3724
    - name: MARLOWE_HEADER_SYNC_PORT
      value: 3725
    - name: MARLOWE_QUERY_PORT
      value: 3726
    - name: MARLOWE_BULK_SYNC_PORT
      value: 3730
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HTTP_PORT
      value: 3784
  
  - name: contract
    image: ghcr.io/functionally/marlowe-contract:latest
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3727
    - name: QUERY_PORT
      value: 3728
    - name: TRANSFER_PORT
      value: 3729
    - name: STORE_DIR
      value: /store
    - name: MARLOWE_CHAIN_SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_CHAIN_SYNC_QUERY_PORT
      value: 3716
    - name: SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_BULK_SYNC_PORT
      value: 3730
    - name: HTTP_PORT
      value: 3786
    volumeMounts:
    - mountPath: /store
      name: contracts
  
  - name: tx
    image: ghcr.io/functionally/marlowe-tx:latest
    depends_on:
    - chain-sync
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3723
    - name: MARLOWE_CHAIN_SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_CHAIN_SYNC_PORT
      value: 3715
    - name: MARLOWE_CHAIN_SYNC_QUERY_PORT
      value: 3716
    - name: MARLOWE_CHAIN_SYNC_COMMAND_PORT
      value: 3720
    - name: CONTRACT_HOST
      value: mrt-preprod
    - name: CONTRACT_QUERY_PORT
      value: 3728
    - name: HTTP_PORT
      value: 3785
  
  - name: proxy
    image: ghcr.io/functionally/marlowe-proxy:latest
    depends_on:
    - marlowe-sync
    - tx
    - contract
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3700
    - name: TRACED_PORT
      value: 3701
    - name: TX_HOST
      value: mrt-preprod
    - name: TX_PORT
      value: 3723
    - name: SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_SYNC_PORT
      value: 3724
    - name: MARLOWE_HEADER_SYNC_PORT
      value: 3725
    - name: MARLOWE_QUERY_PORT
      value: 3726
    - name: CONTRACT_HOST
      value: mrt-preprod
    - name: LOAD_PORT
      value: 3727
    - name: CONTRACT_QUERY_PORT
      value: 3728
    - name: TRANSFER_PORT
      value: 3729
    - name: SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_BULK_SYNC_PORT
      value: 3730
    - name: HTTP_PORT
      value: 3787
    ports:
    - hostPort: 13700
      containerPort: 3700
    - hostPort: 13701
      containerPort: 3701
  
  - name: web-server
    image: ghcr.io/functionally/marlowe-web-server:latest
    depends_on:
    - proxy
    env:
    - name: PORT
      value: 3780
    - name: RUNTIME_HOST
      value: mrt-preprod
    - name: RUNTIME_PORT
      value: 3701
    ports:
    - hostPort: 13780
      containerPort: 3780

  volumes:
  - name: shared
    hostPath:
      type: Directory
      path: ./.
  - name: contracts
    hostPath:
      type: Directory
      path: ./contract.db
  - name: node-db
    hostPath:
      type: Directory
      path: ./node.db

  restartPolicy: Always
