
apiVersion: v1

kind: Pod

metadata:
  name: mrt-preprod
  labels:
    app: mrt-preprod

spec:

  hostname: mrt-preprod

  containers:

  - name: otel-collector
    image: docker.io/otel/opentelemetry-collector-contrib:0.76.1
    args:
    - --config=/etc/otel-collector-config.yml
    ports:
    - hostPort: 14317
      containerPort: 4317
    - hostPort: 14318
      containerPort: 4318
    - hostPort: 18888
      containerPort: 8888
    volumeMounts:
    - mountPath: /etc/otel-collector-config.yml
      name: otel-config
##  resources: {}
##  securityContext:
##    capabilities: {}
##    runAsGroup: 0
##    runAsUser: 0

  - name: node
    image: docker.io/inputoutput/cardano-node:1.35.4
    command:
    - /usr/local/bin/entrypoint
    env:
    - name: NETWORK
      value: preprod
    volumeMounts:
    - mountPath: /ipc
      name: shared
    - mountPath: /data/db
      name: node-db
##  resources: {}
##  securityContext:
##    capabilities: {}
##    runAsGroup: 0
##    runAsUser: 0

  - name: chain-indexer
    image: docker.io/bwbush/marlowe-chain-indexer:20230601a
    depends_on:
    - node
    env:
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    - name: NODE_CONFIG
      value: /ipc/config/node.json
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HTTP_PORT
      value: 3781
    - name: OTEL_SERVICE_NAME
      value: preprod-chain-indexer
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preprod:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 13781
      containerPort: 3781
    volumeMounts:
    - mountPath: /ipc
      name: shared
    - mountPath: /data/db
      name: node-db
##  resources: {}
##  securityContext:
##    capabilities: {}
##    runAsGroup: 0
##    runAsUser: 0

  - name: chain-sync
    image: docker.io/bwbush/marlowe-chain-sync:20230601a
    depends_on:
    - node
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3715
    - name: QUERY_PORT
      value: 3716
    - name: JOB_PORT
      value: 3720
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    - name: NODE_CONFIG
      value: /ipc/config/node.json
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HTTP_PORT
      value: 3782
    - name: OTEL_SERVICE_NAME
      value: preprod-chain-sync
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preprod:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 13715
      containerPort: 3715
    - hostPort: 13716
      containerPort: 3716
    - hostPort: 13720
      containerPort: 3720
    - hostPort: 13782
      containerPort: 3782
    volumeMounts:
    - mountPath: /ipc
      name: shared
##  resources: {}
##  securityContext:
##    capabilities: {}
##    runAsGroup: 0
##    runAsUser: 0

  - name: marlowe-indexer
    image: docker.io/bwbush/marlowe-indexer:20230601a
    depends_on:
    - chain-sync
    env:
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: MARLOWE_CHAIN_SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_CHAIN_SYNC_PORT
      value: 3715
    - name: MARLOWE_CHAIN_SYNC_QUERY_PORT
      value: 3716
    - name: HTTP_PORT
      value: 3783
    - name: OTEL_SERVICE_NAME
      value: preprod-marlowe-indexer
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preprod:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 13783
      containerPort: 3783
##  resources: {}
##  securityContext:
##    capabilities: {}
##    runAsGroup: 0
##    runAsUser: 0

  - name: marlowe-sync
    image: docker.io/bwbush/marlowe-sync:20230601a
    env:
    - name: DB_HOST
      value: host.containers.internal
    - name: DB_USER
      value: cardano
    - name: DB_PASS
      value: bcb33b5c09e31e3dd5a2b4ff0ee111e6
    - name: DB_NAME
      value: preprod
    - name: HOST
      value: mrt-preprod
    - name: MARLOWE_SYNC_PORT
      value: 3724
    - name: MARLOWE_HEADER_SYNC_PORT
      value: 3725
    - name: MARLOWE_QUERY_PORT
      value: 3726
    - name: HTTP_PORT
      value: 3784
    - name: OTEL_SERVICE_NAME
      value: preprod-marlowe-sync
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preprod:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 13724
      containerPort: 3724
    - hostPort: 13725
      containerPort: 3725
    - hostPort: 13726
      containerPort: 3726
    - hostPort: 13784
      containerPort: 3784
##  resources: {}
##  securityContext:
##    capabilities: {}
##    runAsGroup: 0
##    runAsUser: 0
  
  - name: tx
    image: docker.io/bwbush/marlowe-tx:20230601a
    depends_on:
    - chain-sync
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3723
    - name: MARLOWE_CHAIN_SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_CHAIN_SYNC_PORT
      value: 3715
    - name: MARLOWE_CHAIN_SYNC_QUERY_PORT
      value: 3716
    - name: MARLOWE_CHAIN_SYNC_COMMAND_PORT
      value: 3720
    - name: HTTP_PORT
      value: 3785
    - name: OTEL_SERVICE_NAME
      value: preprod-marlowe-tx
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preprod:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 13723
      containerPort: 3723
    - hostPort: 13785
      containerPort: 3785
##  resources: {}
##  securityContext:
##    capabilities: {}
##    runAsGroup: 0
##    runAsUser: 0
  
  - name: contract
    image: docker.io/bwbush/marlowe-contract:20230601a
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3727
    - name: QUERY_PORT
      value: 3728
    - name: STORE_DIR
      value: /store
    - name: HTTP_PORT
      value: 3786
    - name: OTEL_SERVICE_NAME
      value: preprod-marlowe-contract
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preprod:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 13727
      containerPort: 3727
    - hostPort: 13728
      containerPort: 3728
    - hostPort: 13786
      containerPort: 3786
    volumeMounts:
    - mountPath: /store
      name: contracts
##  resources: {}
##  securityContext:
##    capabilities: {}
##    runAsGroup: 0
##    runAsUser: 0
  
  - name: proxy
    image: docker.io/bwbush/marlowe-proxy:20230601a
    depends_on:
    - marlowe-sync
    - tx
    - contract
    env:
    - name: HOST
      value: mrt-preprod
    - name: PORT
      value: 3700
    - name: TRACED_PORT
      value: 3701
    - name: SYNC_HOST
      value: mrt-preprod
    - name: MARLOWE_SYNC_PORT
      value: 3724
    - name: MARLOWE_HEADER_SYNC_PORT
      value: 3725
    - name: MARLOWE_QUERY_PORT
      value: 3726
    - name: CONTRACT_HOST
      value: mrt-preprod
    - name: LOAD_PORT
      value: 3727
    - name: QUERY_PORT
      value: 3728
    - name: TX_HOST
      value: mrt-preprod
    - name: TX_PORT
      value: 3723
    - name: HTTP_PORT
      value: 3787
    - name: OTEL_SERVICE_NAME
      value: preprod-marlowe-proxy
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preprod:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 13700
      containerPort: 3700
    - hostPort: 13701
      containerPort: 3701
    - hostPort: 13787
      containerPort: 3787
##  resources: {}
##  securityContext:
##    capabilities: {}
##    runAsGroup: 0
##    runAsUser: 0
  
  - name: web-server
    image: docker.io/bwbush/marlowe-web-server:20230601a
    depends_on:
    - proxy
    env:
    - name: PORT
      value: 3780
    - name: RUNTIME_HOST
      value: mrt-preprod
    - name: RUNTIME_PORT
      value: 3701
    - name: OTEL_SERVICE_NAME
      value: preprod-marlowe-web-server
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://mrt-preprod:4318
    - name: TZ
      value: UTC
    ports:
    - hostPort: 13780
      containerPort: 3780
##  resources: {}
##  securityContext:
##    capabilities: {}
##    runAsGroup: 0
##    runAsUser: 0

  volumes:
  - name: otel-config
    hostPath:
      type: File
      path: ./config/otel-collector-config.yml
  - name: shared
    hostPath:
      type: Directory
      path: ./.
  - name: contracts
    hostPath:
      type: Directory
      path: ./contracts
  - name: node-db
    hostPath:
      type: Directory
      path: ./node.db

  restartPolicy: Always
  enableServiceLinks: false
  automountServiceAccountToken: false

status: {}

